config/routes.rb
Rails.application.routes.draw do
  devise_for :end_users
  
  root to:'homes#top'
  get 'about', to:'homes#about'
  get 'info', to:'homes#info'
  
  resources:genre,only:[:index,:create,:edit,:update,:destroy]
  resources:type,only:[:index,:create,:edit,:update,:destroy]
  resources:record do
   collection do
    get '/calendar'=>"record#calendar"
    get '/search'=>"record#search"
   end
  end
  resources:food
  resources:pet
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_aboutlink.html.erb
<%= link_to about_path, class:"h4 text-reset" do %>
    <div class = "text-right mr-3 mt-2"><i class="fas fa-cog"></i>
    </div>
<% end %>

app/views/shared/_calendar.html.erb
<div class="table-responsive" id="calendar">
<div class="calendar">
<%= month_calendar events: @record_cale do |date, records| %>
  <%= date.day %>
  <% @record_cale.each do |record| %>
   <%if record.created_at.strftime('%Y-%m-%d') == date.strftime('%Y-%m-%d') %> 
    <div>
     <%= link_to record_path(record), class:"btn btn-sm btn-primary px-3 rounded-pill my-1" do %>
      <%= record.pet.name.slice(0)%>
     <% end %>
    </div>
   <% end %>
  <% end %>
  
<% end %>
</div>

</div>

app/views/shared/_container.html.erb
<div class = "container-lg">
  
</div>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_modal_edit.html.erb
<%= form_with model: record do |f| %>

 <%#= render 'shared/errors', model: f.object %>

 <div class="form-group">
  <%= f.label :うちの子の名前 %>
  <%= f.collection_select :pet_id, Pet.all, :id, :name, options = { include_blank: "選択してください" } %>
 </div>
 
 <div class="form-group">
  <%= f.label :フード名 %>
  <%= f.collection_select :food_id, Food.all, :id, :name, options = { include_blank: "選択してください" } %>
 </div>
 
 <div class="form-group">
  <%= f.label :摂取量 %>
  <%= f.select :amount,[["完食","完食"], ["半分","半分"], ["全部残した","全部残した"]], include_blank: "選択して下さい" %>
 </div>
 
 <div class="form-group">
  <%= f.label :メモ %>
  <%= f.text_area :memo %>
 </div>
 
  <%= f.submit '記録を更新する', class:"btn btn-info mb-3" %>
  <%#= link_to "削除",record_path(record.id),method: :delete,class:"btn btn-danger mb-3" %>
 
<% end %>

app/views/shared/_modal_genre.html.erb
<div class="js-genre-errors"></div>

<%= form_with model: genre, url: '/genre', method: :post, local: false do |f| %>
 
 <%= f.label :ジャンル名 %>
 <%= f.text_field :name, class:"name" %>
 <%= f.submit '新規登録', class:"btn btn-info" %>
<% end %>

app/views/shared/_modal_record.html.erb
<div class = "title">
 <h5><strong><%= @record.pet.name %>ちゃんの記録</strong></h5>
</div>
<br>

<% @recorda.each do |record| %>
 <%if record.pet_id == @record.pet.id && 
  record.created_at.strftime('%Y/%m/%d') == @record.created_at.strftime('%Y/%m/%d') %> 
 <div>
 <span><%= record.created_at.strftime('%Y/%m/%d %H:%M') %></span>
 <span><%= record.pet.name %></span>
 <span><%= record.food.name %></span>
 <span><%= record.amount %></span>
 <span><%= record.memo %></span>
 </div>
 <% end %>
<% end %>

<div>
<%= link_to "記録一覧に戻る",record_index_path, class:"btn btn-sm btn-secondary" %>
<%= link_to "カレンダーに戻る",calendar_record_index_path, class:"btn btn-sm btn-secondary" %>
</div>

<br>

app/views/shared/_modal_type.html.erb
<div class="js-type-errors"></div>

<%= form_with model: type, url: '/type', method: :post, local: false do |f| %>

 <%= f.label :タイプ %>
 <%= f.text_field :name %>
 <%= f.submit '新規登録',class:"btn btn-info" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
 <div class="container">
  <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
   <ul class="navbar-nav ml-auto">
    <% if end_user_signed_in? %>
     <li class="nav-item">
      <%= link_to "ウチの子",pet_index_path, class: 'nav-link text-dark' %>
     </li>
     <li class="nav-item">
      <%= link_to "記録",record_index_path, class: 'nav-link text-dark' %>
     </li>
     <li class="nav-item">
      <%= link_to "フード",food_index_path, class: 'nav-link text-dark' %>
     </li>
     <li class="nav-item">
      <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class: 'nav-link text-dark' %>
     </li>
    <% else %>
     <li class="nav-item">
      <%= link_to "ホーム",pet_index_path, class: 'nav-link text-dark' %>
     </li>
     <li class="nav-item">
      <%= link_to "ログイン",pet_index_path, class: 'nav-link text-dark' %>
     </li>
     <li class="nav-item">
      <%= link_to "新規登録",pet_index_path, class: 'nav-link text-dark' %>
     </li>
    <% end %>
   </ul>
  </div>
 </div>
</nav>

app/views/shared/_recordindex.html.erb
 <%= render 'shared/aboutlink' %>
 
<div class = "container-lg">

<%= link_to new_record_path, class:"btn btn-warning btn-lg btn-block" do %>
 <i class="fas fa-pen"></i>
 記録する
 <i class="fas fa-pen"></i>
<% end %>

<div class = "search mt-3">
 <%= form_with url: search_record_index_path, local: true, method: :get do |form| %>
  <%= form.collection_select :pet_id, @pets, :id, :name, options = { include_blank: "名前で検索" } %>
  <%= form.submit "検索" %>
  <%= link_to "一覧に戻る",record_index_path, class:"btn btn-sm btn-secondary" %>
 <% end %>
</div>

<% if @records.count == 0 %>
 <div class = "m-3"><span class = "text-dark">記録がありません</span></div>
<% else %>
<div class="table-responsive">
<table class="table text-nowrap table-light table-striped mt-3">
<% @records.each do |record| %>

 <tr>
  <th colspan = "5" >
   <%= record.created_at.strftime('%Y/%m/%d %H:%M') %>
   <%= link_to edit_record_path(record) do %>
     <i class="fas fa-edit"></i>
   <% end %>
  </th>
 </tr>
 <tr>
  <th style="width: 20%">
   <div class = "mb-2">
    <%= image_tag record.pet.get_pet_image(50,50),class:"rounded-circle mx-3" %>
   </div>
   <span class = "ml-3"><%= record.pet.name %></span>
  </th>
  <td style="width:20%">
   <div class = "mt-3">
    <div><%= record.food.name %></div>
    <span class = '<%= amount_color(record) %>'><%= record.amount %></span>
   </div>
  </td>
  <td>
   <!--モーダルメモ-->
   <div class = "mt-3">
     <a class="btn btn-sm btn-secondary" type="button" data-toggle="collapse" href=<%= "#collapse".concat(record.id.to_s) %>
       aria-expanded="false" aria-controls=<%= "collapse".concat(record.id.to_s) %>>
        memo
     </a>
     <div class="collapse" id=<%= "collapse".concat(record.id.to_s) %> >
      <%= record.memo %>
     </div>
   </div>
  </td>
  
  </tr>
 <% end %>

</table>
</div>
<% end %>

<div><%= paginate @records, theme: 'twitter-bootstrap-4' %></div>

</div>