config/routes.rb
Rails.application.routes.draw do
  devise_for :end_users
  
  root to:'homes#top'
  get 'about', to:'homes#about'
  get 'info', to:'homes#info'
  
  resources:genre,only:[:index,:create,:edit,:update,:destroy]
  resources:type,only:[:index,:create,:edit,:update,:destroy]
  resources:record do
   collection do
    get '/calendar'=>"record#calendar"
    get '/search'=>"record#search"
   end
  end
  resources:food
  resources:pet
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
  def info
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class = "container-lg">

<div class = "bg-light my-3 pt-3">

 <div class = "mx-3">
  <table class = "table" >
   <tr>
    <td>
     <%= link_to genre_index_path, class:"text-reset" do %>
      フードジャンル編集
      <span class = "text-right"><i class="fas fa-angle-right"></i></span>
     <% end %>
    </td>
   </tr>
   <tr>
    <td>
     <%= link_to type_index_path, class:"text-reset" do %>
      フードタイプ編集
      <span class = "text-right"><i class="fas fa-angle-right"></i></span>
     <% end %>
    </td>
   </tr>
   <tr>
    <td>
     <%= link_to "戻る", :back, class:"btn btn-secondary" %>
    </td>
   </tr>
  </table>
 </div>

</div>

</div>

app/views/homes/top.html.erb
<div class = "position-relative">
 
 <div id="container">
   <div id="theTarget">
    <div class="image1"></div>
    <div class="image2"></div>
    <div class="image3"></div>
   </div>
 </div>
 
 <div class = "position-absolute text-center col-lg-12 text-light texta">
  <div class = "textline">「昨日ウチの子何食べたっけ？」</div>
  <div class = "textline-b">大切なペットのために食事管理を。</div>
  <!--そんなあなたのための「ウチの子」です。-->
 </div>
 
</div>

<br><br>
<div class = "container-lg">
<% if end_user_signed_in? %>
   <div class = "link">
    <span>STEP1</span>
    <%= link_to "ウチの子を登録しよう", new_pet_path, class:'nav-link text-dark' %>
   </div>
   <div class = "link">
    <span>STEP2</span>
    <%= link_to "フードを登録しましょう", new_food_path, class:'nav-link text-dark'%>
   </div>
   <div class = "link">
    <span>STEP3</span>
    <%= link_to "記録しましょう" ,new_record_path, class:'nav-link text-dark' %>
   </div>
<% else %>
 <%= link_to "ログイン",new_end_user_session_path, class:"btn btn-dark btn-lg btn-block mb-3" %>
 <%= link_to "新規登録",new_end_user_registration_path, class:"btn btn-primary btn-lg btn-block mb-3" %>
<% end %>
</div>
</div>

<br><br><br>