config/routes.rb
Rails.application.routes.draw do
  devise_for :end_users
  
  root to:'homes#top'
  get 'about', to:'homes#about'
  get 'info', to:'homes#info'
  
  resources:genre,only:[:index,:create,:edit,:update,:destroy]
  resources:type,only:[:index,:create,:edit,:update,:destroy]
  resources:record do
   collection do
    get '/calendar'=>"record#calendar"
    get '/search'=>"record#search"
   end
  end
  resources:food
  resources:pet
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :end_user
  has_many :records, dependent: :destroy
  has_many :foods, through: :records
  has_one_attached :pet_image
  
  def get_pet_image(width, height)
   unless pet_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    pet_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
    pet_image.variant(resize: "#{width}x#{height}").processed
  end
  
  validates :name, presence: true,length: { minimum: 1, maximum: 10 }
  validates :memo, length: { maximum: 30 }
  
  enum gender: { man: 0, woman: 1}
  
end

app/controllers/pet_controller.rb
class PetController < ApplicationController
 before_action :set_pet, only: [:show, :edit, :update, :destroy]
 before_action :set_url, only: [:show, :edit, :update, :destroy]
 
  def new
   @pet = Pet.new
  end
 
 def create
   @pet = Pet.new(pet_params)
   @pet.end_user_id = current_end_user.id
   if @pet.save
    redirect_to pet_index_path
   else
    render:new
   end
 end

  def index
   @pets = Pet.all
   @pets = current_end_user.pets
  end
 
  def show
   @record = Record.find(params[:id])
   @pets = current_end_user.pets
   @foods = current_end_user.foods
   @pet = Pet.find(params[:id])
  end
  
  def edit
   @pet = Pet.find(params[:id])
  end
  
  def update
   @pet = Pet.find(params[:id])
   if @pet.update(pet_params)
    redirect_to pet_index_path(@pet.id)
   else
    render:edit
   end
  end
  
  def destroy
   @pet = Pet.find(params[:id])
   @pet.destroy
   redirect_to pet_index_path
  end
  
  private
  #直叩き防止
  def set_pet
      @pet = Pet.find(params[:id])
  end

  def set_url
    if @pet.end_user_id != current_end_user.id
      redirect_to new_end_user_session_path
    end
  end
  
  # ストロングパラメータ
  def pet_params
    params.require(:pet).permit(:name,:pet_image,:age,:birthday,:gender,:memo)
  end
  
end

app/helpers/pet_helper.rb
module PetHelper
end

app/views/pet/edit.html.erb
 <%= render 'shared/aboutlink' %>

<div class = "container-lg">

<%= form_with model: @pet do |f| %>
 <%= render 'shared/errors', model: f.object %>

 <div class="form-group">
  <%= f.label :ウチの子の写真 %>
  <%= f.file_field :pet_image,accept:"image/*" %>
 </div>
 <div class="form-group">
  <%= f.label :名前 %>
  <%= f.text_field :name %>
 </div>
 <div class="form-group">
  <%= f.label :年齢 %>
  <%= f.select :age, *[0..30], prompt:"--" %>
 </div>
 <div class="form-group">
  <%= f.label :誕生日 %>
  <%= f.date_select :birthday, use_month_numbers: true, prompt:"--",
     start_year: 1990, end_year: (Time.now.year), default: Date.new(1989, 1, 1) %>

 </div>
 <div class="form-group">
	<%= f.label :性別 %>
  <%= f.radio_button :gender,"man" %>
  <%= f.label :gender, "オス" %>
  <%= f.radio_button :gender, "woman" %>
  <%= f.label :gender, "メス"%>
 </div>
 <div class="form-group">
  <%= f.label :メモ %>
  <%= f.text_area :memo %>
 </div>
	
  <%= f.submit '変更を保存する', class:"btn btn-info mb-3" %>
  <%= link_to '削除', pet_path(@pet.id), method: :delete, 
    "data-confirm" => "これまでの記録も全て削除されます。本当に削除しますか？", class:"btn btn-danger mb-3" %>
  
<% end %>

</div>

app/views/pet/index.html.erb
 <%= render 'shared/aboutlink' %>

<div class="text-right">
 <%= link_to new_pet_path, method: :get, class:"btn btn-warning mr-3 my-3" do %>
  <i class="fas fa-paw"></i>
   ウチの子を登録する
  <i class="fas fa-chevron-right"></i>
 <% end %>
</div>
 

<div class = "container-lg">

<% @pets.each do |pet| %>

<div class ="border shadow pet_log my-3 bg-light">

<div class = "row">
 
 <div class = "col-sm-6">
  <div class = "mt-3 mx-3">
    <%= image_tag pet.get_pet_image(200,200),class:"rounded-circle mx-3" %>
    <div class = "row justify-content-center"> 
     <%= link_to edit_pet_path(pet) do %>
      <i class="fas fa-edit"></i>
     <% end %>
    </div>
  </div>
 
 <table class="table">
  <tr>
   <th>名前</th>
   <td><%= pet.name %></td>
  </trt>
  <tr>
   <th>年齢</th>
   <td>
   <% if pet.age == nil %>
     no date
   <% else %>
    <%= pet.age %>歳
   <% end %>
   </td>
  </tr>
  <tr>
   <th nowrap>誕生日</th>
   <td class = "btd">
    <% if pet.age == nil %>
     no date
    <% else %>
     <%= pet.birthday %>
    <% end %>
   </td>
  </tr>
  <tr>
   <th>性別</th>
   <td>
    <% if pet.age == nil %> 
     no date
    <% else %>  
     <%= pet.gender_i18n %>
    <% end %>
   </td>
  </tr>
  <tr>
   <th>メモ</th>
   <td><%= pet.memo %></td>
  </tr>
  <tr><th></th><td></td></tr>
 </table>
</div>

<div class = "col-sm-6">
 <div class = "h5 py-3 text-center"><span class = "liner">
  <i class="fas fa-paw"></i><%= pet.name %>ちゃんの記録<i class="fas fa-paw"></i>
  </span></div>
 
 <div class = "my-3"><%= pie_chart pet_foots_per(pet), suffix: "%" %></div>
</div>

</div>
</div>

<% end %>

</div>

app/views/pet/new.html.erb
 <%= render 'shared/aboutlink' %>

<div class = "container-lg">

<%= form_with model: @pet, url: '/pet', method: :post do |f| %>
  
  <%= render 'shared/errors', model: f.object %>
 
 <div class="form-group">
  <%= f.label :ウチの子の写真 %>
  <%= f.file_field :pet_image,accept:"image/*" %>
 </div>
 <div class="form-group">
  <%= f.label :名前 %>
  <%= f.text_field :name %>
 </div>
 <div class="form-group">
  <%= f.label :年齢 %>
  <%= f.select :age, *[0..30], prompt:"--" %>
 </div>
 <div class="form-group">
  <%= f.label :誕生日 %>
  <%= f.date_select :birthday, use_month_numbers: true,prompt:"--",
     start_year: 1992, end_year: (Time.now.year) %>
     <!--, default: Date.new(1989, 1, 1)-->
     <!--, date_separator: '%s'),'年','月')+'日'-->

 </div>
 <div class="form-group">
	<%= f.label :性別 %>
  <%= f.radio_button :gender,"man" %>
  <%= f.label :gender, "オス" %>
  <%= f.radio_button :gender, "woman" %>
  <%= f.label :gender, "メス"%>
 </div>
 <div class="form-group">
  <%= f.label :メモ %>
  <%= f.text_area :memo %>
 </div>
	
  <%= f.submit '登録する',class:"btn btn-info mb-3" %>
<% end %>

</div>

app/views/pet/show.html.erb
<!--<%# @pets.each do |pet| %>-->

<!--<div class ="border shadow pet_log my-3">-->

<!--<div class = "row">-->
 
<!-- <div class = "col-sm-6">-->
<!--  <div class = "my-3 mx-3">-->
<!--    <%#= image_tag pet.get_pet_image(200,200),class:"rounded-circle mx-3" %>-->
<!--    <div class = "row justify-content-center"> -->
<!--     <%#= link_to edit_pet_path(pet) do %>-->
<!--      <i class="fas fa-edit"></i>-->
<!--     <#%end %>-->
<!--    </div>-->
<!--  </div>-->
 
<!-- <table class="table">-->
<!--  <tr>-->
<!--   <th>名前</th>-->
<!--   <td><#%= pet.name %></td>-->
<!--  </trt>-->
<!--  <tr>-->
<!--   <th>年齢</th>-->
<!--   <td><#%= pet.age %>歳</td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--   <th>誕生日</th>-->
<!--   <td class = "btd"><%= pet.birthday %>生まれ</td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--   <th>性別</th>-->
<!--   <td><%= pet.gender_i18n %></td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--   <th>メモ</th>-->
<!--   <td><%= pet.memo %></td>-->
<!--  </tr>-->
<!--  <tr><th></th><td></td></tr>-->
<!-- </table>-->
<!--</div>-->

<!--<div class = "col-sm-6">-->
<!-- <br><br>-->
<!-- <div class = "h4 py-3 text-center"><span class = "liner">-->
<!--  <i class="fas fa-paw"></i><%= pet.name %>ちゃんの記録<i class="fas fa-paw"></i>-->
<!--  </span></div>-->
<!-- <div class = "my-3"><%= pie_chart pet.foods.group(:name).count %></div>-->
<!--</div>-->

<!--</div>-->
<!--</div>-->

<!--<% end %>-->

<!--<div class = "text-center">-->
<!-- <%= link_to "ウチの子一覧に戻る", pet_index_path, class:"btn btn-secondary my-3" %>-->
<!--</div>-->